CREATE DATABASE IF NOT EXISTS empresarial;

USE empresarial;

CREATE TABLE TB_TIPO_DOCUMENTO(
    TIP_DOC_ID INTEGER NOT NULL PRIMARY KEY,
	TIP_DOC_TIPO VARCHAR(100) NOT NULL
);

CREATE TABLE TB_DOCUMENTO(
    DOC_ID INTEGER NOT NULL PRIMARY KEY,
	DOC_NOME VARCHAR(100),
	DOC_TIPO_DOCUMENTO_ID INTEGER NOT NULL,
	CONSTRAINT FOREIGN KEY (DOC_TIPO_DOCUMENTO_ID) REFERENCES TB_TIPO_DOCUMENTO(TIP_DOC_ID)
);	

CREATE TABLE TB_DEPARTAMENTO(
    DEP_ID INTEGER NOT NULL PRIMARY KEY,
	DEP_NOME VARCHAR(100)
);

CREATE TABLE TB_USUARIO(
    USU_ID INTEGER NOT NULL PRIMARY KEY,
	USU_NOME VARCHAR(100),
	USU_SOBRENOME VARCHAR(100) NOT NULL,
	USU_SENHA VARCHAR(20) NOT NULL,
	USU_DEPARTAMENTO_ID INTEGER NOT NULL,
	CONSTRAINT FOREIGN KEY (USU_DEPARTAMENTO_ID) REFERENCES TB_DEPARTAMENTO(DEP_ID)
);

CREATE TABLE TB_MOVIMENTO_DOCUMENTO(
    MOV_DOC_ID INTEGER NOT NULL,
	MOV_DOC_OBSERVACAO VARCHAR(100),
	MOV_DOC_DATA_MOVIMENTACAO DATETIME NOT NULL,
	MOV_DOC_USUARIO_ID_ORIGEM INTEGER NOT NULL,
	CONSTRAINT FOREIGN KEY (MOV_DOC_USUARIO_ID_ORIGEM) REFERENCES TB_USUARIO(USU_ID),
	MOV_DOC_USUARIO_ID_DESTINATARIO INTEGER NOT NULL,
	CONSTRAINT FOREIGN KEY (MOV_DOC_USUARIO_ID_DESTINATARIO) REFERENCES TB_USUARIO(USU_ID),
	MOV_DOC_DOCUMENTO_ID INTEGER NOT NULL,
	CONSTRAINT FOREIGN KEY (MOV_DOC_DOCUMENTO_ID) REFERENCES TB_DOCUMENTO(DOC_ID)
);

INSERT INTO TB_TIPO_DOCUMENTO (TIP_DOC_ID,TIP_DOC_TIPO) VALUES (1,"Requerimento");
INSERT INTO TB_TIPO_DOCUMENTO (TIP_DOC_ID,TIP_DOC_TIPO) VALUES (2,"Ofício");

INSERT INTO TB_DOCUMENTO (DOC_ID,DOC_NOME,DOC_TIPO_DOCUMENTO_ID) VALUES (1,"Serviços de manutenção",1);
INSERT INTO TB_DOCUMENTO (DOC_ID,DOC_NOME,DOC_TIPO_DOCUMENTO_ID) VALUES (2,"Comunicado",2);

INSERT INTO TB_DEPARTAMENTO (DEP_ID,DEP_NOME) VALUES (1,"Manutenção");
INSERT INTO TB_DEPARTAMENTO (DEP_ID,DEP_NOME) VALUES (2,"RH");

INSERT INTO TB_USUARIO (USU_ID,USU_NOME,USU_SOBRENOME,USU_SENHA,USU_DEPARTAMENTO_ID) VALUES (1,"Giuliano","Sacoman de Barros","123456",1);
INSERT INTO TB_USUARIO (USU_ID,USU_NOME,USU_SOBRENOME,USU_SENHA,USU_DEPARTAMENTO_ID) VALUES (2,"Marcos","Pereira Barbos","135790",2);

INSERT INTO TB_MOVIMENTO_DOCUMENTO (MOV_DOC_ID,MOV_DOC_OBSERVACAO,MOV_DOC_DATA_MOVIMENTACAO,MOV_DOC_USUARIO_ID_ORIGEM, MOV_DOC_USUARIO_ID_DESTINATARIO, MOV_DOC_DOCUMENTO_ID) 
VALUES (1,"O documento demorou ser entregue",'2018-2-3 16:18:30',1,2,1);
INSERT INTO TB_MOVIMENTO_DOCUMENTO (MOV_DOC_ID,MOV_DOC_OBSERVACAO,MOV_DOC_DATA_MOVIMENTACAO,MOV_DOC_USUARIO_ID_ORIGEM, MOV_DOC_USUARIO_ID_DESTINATARIO, MOV_DOC_DOCUMENTO_ID) 
VALUES (2,"O documento chegou faltando páginas",'2018-2-3 16:18:30',2,1,1);


