CREATE DATABASE IF NOT EXISTS empresarial;

USE empresarial;

CREATE TABLE TB_TIPO_DOCUMENTO(
    TIP_DOC_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TIP_DOC_TIPO VARCHAR(100) NOT NULL
);

CREATE TABLE TB_DOCUMENTO(
    DOC_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DOC_NOME VARCHAR(100),
	DOC_TIPO_DOCUMENTO_ID INTEGER NOT NULL,
	CONSTRAINT FOREIGN KEY (DOC_TIPO_DOCUMENTO_ID) REFERENCES TB_TIPO_DOCUMENTO(TIP_DOC_ID)
);	

CREATE TABLE TB_DEPARTAMENTO(
    DEP_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DEP_NOME VARCHAR(100)
);

CREATE TABLE TB_USUARIO(
    USU_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USU_NOME VARCHAR(100),
	USU_SOBRENOME VARCHAR(100) NOT NULL,
	USU_SENHA VARCHAR(20) NOT NULL,
	USU_DEPARTAMENTO_ID INTEGER NOT NULL,
	CONSTRAINT FOREIGN KEY (USU_DEPARTAMENTO_ID) REFERENCES TB_DEPARTAMENTO(DEP_ID)	
);

CREATE TABLE TB_MOVIMENTO_DOCUMENTO(
    MOV_DOC_ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MOV_DOC_OBSERVACAO VARCHAR(100),
	MOV_DOC_DATA_MOVIMENTACAO DATETIME NOT NULL,
	MOV_DOC_USUARIO_ID_ORIGEM INTEGER NOT NULL,
	CONSTRAINT FOREIGN KEY (MOV_DOC_USUARIO_ID_ORIGEM) REFERENCES TB_USUARIO(USU_ID),
	MOV_DOC_USUARIO_ID_DESTINATARIO INTEGER NOT NULL,
	CONSTRAINT FOREIGN KEY (MOV_DOC_USUARIO_ID_DESTINATARIO) REFERENCES TB_USUARIO(USU_ID),
	MOV_DOC_DOCUMENTO_ID INTEGER NOT NULL,
	CONSTRAINT FOREIGN KEY (MOV_DOC_DOCUMENTO_ID) REFERENCES TB_DOCUMENTO(DOC_ID)
);

INSERT INTO TB_DEPARTAMENTO (DEP_ID,DEP_NOME) VALUES (1,"Vendas");
INSERT INTO TB_DEPARTAMENTO (DEP_ID,DEP_NOME) VALUES (2,"Compras");
INSERT INTO TB_DEPARTAMENTO (DEP_ID,DEP_NOME) VALUES (3,"Recuros Humanos");
INSERT INTO TB_DEPARTAMENTO (DEP_ID,DEP_NOME) VALUES (4,"Administrativo");
INSERT INTO TB_DEPARTAMENTO (DEP_ID,DEP_NOME) VALUES (5,"Cobrança");